# Generated by Django 4.0.3 on 2022-05-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sub_image_profile_subimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.TextField(default=1, verbose_name='仕事'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(default=1, verbose_name='自己紹介'),
            preserve_default=False,
        ),
    ]
